# Generated by Django 4.1.1 on 2023-03-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_restaurant_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_reg',
            name='id_proof',
        ),
    ]
