# Generated by Django 4.1.1 on 2023-03-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_add_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_reg',
            name='oname',
        ),
        migrations.AddField(
            model_name='add_reg',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
