# Generated by Django 4.1.1 on 2023-03-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0008_add_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_loc',
            name='ctime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_loc',
            name='otime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
