# Generated by Django 4.1.1 on 2023-03-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0010_add_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_loc',
            name='user',
        ),
    ]
