# Generated by Django 4.1.1 on 2023-03-08 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0011_remove_add_loc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_loc',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.restaurant_reg'),
        ),
    ]
