# Generated by Django 4.1.1 on 2023-03-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0012_add_loc_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_photo',
            name='user',
        ),
    ]
