# Generated by Django 4.1.1 on 2023-03-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0014_add_photo_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_menu',
            name='user',
        ),
    ]
