# Generated by Django 4.1.1 on 2023-03-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0016_add_menu_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_reg',
            name='raddress',
        ),
    ]
