# Generated by Django 4.1.1 on 2023-03-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0019_add_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_events',
        ),
    ]
