# Generated by Django 4.1.1 on 2023-03-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0021_add_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('edes', models.CharField(max_length=1000, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.restaurant_reg')),
            ],
        ),
    ]
