# Generated by Django 4.1.1 on 2023-03-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0022_add_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_event',
        ),
    ]
