# Generated by Django 4.1.1 on 2023-03-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0024_add_articles_add_specials_add_shefs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_articles',
        ),
    ]
