# Generated by Django 4.1.1 on 2023-03-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0030_add_menu_availability_delete_add_shefs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_events',
        ),
    ]
