# Generated by Django 4.1.1 on 2023-03-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0031_delete_add_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_reg',
            name='license',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
