# Generated by Django 4.1.1 on 2023-03-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0032_restaurant_reg_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_reviews',
            name='user',
        ),
        migrations.AddField(
            model_name='customer_reviews',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
